### ISSUE TITLE
Revise and refresh dates as data episode

### ISSUE THREAD

**Issue by morskyjezek** [LibraryCarpentry/lc-spreadsheets#130]
As of June 2022, there have been a few suggestions and corrections regarding the "Dates as Data" episode, including issues #66 , #69 , #127 , and #125 . Many of these have been outstanding for a while, so I'd like to work on closing them. Since there are multiple in reference to one episode, I working on responses in a new branch: https://github.com/LibraryCarpentry/lc-spreadsheets/tree/address-date-episode-issues-june2022 . 

As I was working through the open issues, I also encountered many spots that needed copyediting (errant commas, unclosed brackets, wordings that could be made clearer) and have included those changes with the new branch. 

Before merging, I'd like to put this out there to the maintainers group ( @LibraryCarpentry/lc-spreadsheets-maintainers ) for any comments, additional pointers, or objections. Please comment on this issue, or propose changes or edits on the branch.

**Comment by morskyjezek** [comment]
As part of this, I'd propose that we remove some of the unhelpfully judgmental language in the dates episode. 

1. For example, the sentence "Spreadsheet programs have numerous 'useful features' which allow them to 'handle' dates in a variety of ways." is presumably intended to be sarcastic, but the inclusion of quotation marks may make some readers wonder if these are quotations from an uncited work? 

2. The "Key Point" of "Excel is notoriously bad at handling dates" should probably be changed to something like "The ways that spreadsheet programs process date information can cause unintended, or unknown, ambiguities to data, which can cause the date information to change when exchanged between different users, programs, and operating systems."

The goals and objectives of the lesson are obscured by making value judgments toward the various spreadsheet programs. The point is that Excel does things with dates that may not be first suspected, and so will the other programs. Is that frustrating? Yes! But learners should come away from this lesson with an understanding of the ways that spreadsheets store and format dates, how that raises ambiguities with date information, and a working knowledge of some ways to make their spreadsheets more accessible and interoperable, therefore less ambiguous. 

Thoughts or rebuttals welcome.

**Comment by morskyjezek** [comment]
Interesting day of year calendar examples:

- https://www.esrl.noaa.gov/gmd/grad/neubrew/Calendar.jsp
- https://nsidc.org/support/faq/day-year-doy-calendar

I find the DOY approach quite field specific. It is useful here since data librarians may be working with researchers from many different fields. However, it would be useful to have a bit more context about which disciplines might use this approach more (or less). For example, is it widely used in climate science, meteorology, and weather observations? Other areas?

**Comment by morskyjezek** [comment]
Progress so far (reflected in the new branch):

- [ ] Issue #66 - request to add information about how to convert a numerical value to a date value; also, provoked idea to create a section devoted to basic Excel functions for working with dates. 
- [ ] Issue #69 - as suggested the "preferred formatting" section is moved down to the end of the lesson (makes more sense as the main point, and also the main actionable item of this episode)
- [ ] Issue #127 - missing comma typo corrected (merged in pull 129 https://github.com/LibraryCarpentry/lc-spreadsheets/pull/129 )
- [ ] Issue #125 - corrected typo, but also made other language and text revisions throughout the lesson, including unnecessary commas, unclosed brackets, and a general copyedit.

**Comment by morskyjezek** [comment]
This was merged after consultation amongst the lesson maintainers. Please post any additional changes or new proposals in new issues.
