### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [LibraryCarpentry/lc-spreadsheets#35]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [ ] Example code chunks run as expected
- [ ] Challenges / exercises run as expected
- [ ] Challenge / exercise solutions are correct
- [ ] Call out boxes (exercises, discussions, tips, etc) render correctly
- [x] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [x] Each episode includes learning objectives
- [x] Each episode includes questions
- [ ] Each episode includes key points
- [ ] Setup instructions are up-to-date, correct, clear, and complete
- [ ] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [ ] Some Instructor notes are provided
- [x] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by ErinBecker** [comment]
Hi Maintainers - Just confirming whether you're planning on including your lesson in the June 2019 release. We'll be putting out a blog post tomorrow inviting contributors to work on issues that have been tagged as part of the release milestone, so if there are specific issues you're looking for community help with, please add them to that milestone. I'll go ahead and do that too for any issues that are currently marked "help-wanted". Please let me know if you have any questions!

**Comment by shlake** [comment]
@ErinBecker my maintainers and I are working on getting this lesson ready for the June2019 release. We plan working during the Mozilla-Library Carpentry sprint, as well as other times leading up to the sprint.

**Comment by ErinBecker** [comment]
Thanks for confirming @shlake! I'll go ahead and include this lesson in the upcoming blog post asking for contributions to the Milestone issue list.

**Comment by tpatwood** [comment]
Went through and confirmed the lesson links work as expected! I wonder about linking out to a book on Amazon (here: https://librarycarpentry.org/lc-spreadsheets/00-intro/index.html#what-this-lesson-will-not-teach-you). I'll add this as an issue to see if we can find an OA alternative, which would be in line with the rest of the lesson (as far as I can tell!) but I'm open to it staying the same if we can't find a good alternative.

**Comment by libcce** [comment]
@shlake @tpatwood do you think the lesson is ready for the June 4 lesson release deadline? Let me know if you need me to help with anything?

**Comment by shlake** [comment]
@libcce I do not think it is ready. I sprinted as much as I could last week. There are issues that need to be resolved as well as updating other pages. Those did not get touched during the sprint and will not be done by the June 4th deadline.

We tried, but......  When will be the next release date?

**Comment by libcce** [comment]
@shlake So much work was done on this lesson! It was amazing to see! Thanks so much to you and everyone else that updated the lesson during the sprint 😄 @ErinBecker @fmichonneau would be the best people to ask when the next release will be but I'm sure it is too soon. Having at least 3-6 months more to work on the lesson will probably be helpful.

**Comment by ErinBecker** [comment]
Thanks for the update @shlake. I loved seeing all of the progress on this lesson over the sprint. Sorry you won't make the release deadline this time around. I don't know when the next release will be, but at least 6 months from now at the earliest. Please go ahead and close this issue and we'll open a new one when the next release is planned. 😄

**Comment by shlake** [comment]
Will definitely do more work on this lesson and be ready for the next release.
